# Generated by Django 4.0.4 on 2022-04-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalvalidation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='client',
            name='validation',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='validation',
        ),
        migrations.AddField(
            model_name='client',
            name='id_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='client',
            name='license_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='professional',
            name='cv_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='professional',
            name='id_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='professional',
            name='license_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='ClientValidation',
        ),
        migrations.DeleteModel(
            name='ProfessionalValidation',
        ),
    ]
