# Generated by Django 3.1.2 on 2022-04-30 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220429_0655'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Institution',
        ),
        migrations.RenameModel(
            old_name='Professional',
            new_name='Locum',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_client',
            new_name='is_institution',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_professional',
            new_name='is_locum',
        ),
    ]
