# Generated by Django 3.1.2 on 2022-04-30 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220430_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='locum',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='id_file',
            field=models.FileField(null=True, upload_to='validation/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='license_file',
            field=models.FileField(null=True, upload_to='validation/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='locum',
            name='cv_file',
            field=models.FileField(null=True, upload_to='validation/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='locum',
            name='id_file',
            field=models.FileField(null=True, upload_to='validation/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='locum',
            name='license_file',
            field=models.FileField(null=True, upload_to='validation/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='locum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
