# Generated by Django 3.1.2 on 2022-05-06 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('salary', models.FloatField()),
                ('job_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('SHIFT', 'Shift')], max_length=20, null=True)),
                ('expiry_date', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jobs', models.ManyToManyField(to='loccumApi.Job')),
            ],
            options={
                'ordering': ['cart_id', '-created_at'],
            },
        ),
    ]
