# Generated by Django 3.1.2 on 2022-05-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loccumApi', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
    ]
