# Generated by Django 3.1.2 on 2022-05-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loccumApi', '0003_auto_20220519_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('FullTime', 'FullTime'), ('Shift', 'Shift')], max_length=20, null=True),
        ),
    ]
