# Generated by Django 3.1.2 on 2022-05-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loccumApi', '0004_auto_20220523_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='%m%d%y/job_profile'),
        ),
    ]
